fix(PluginResolver.ts): add ./node_modules to module load path
honkit/honkit pull request #134
Opened 2020-09-30 13:10 UTC by dogatana

change the order to resolve a package location as follows

- try ./node_modules first (added)
- try baseDir next (original)

This is a solution for #133

2020-09-30 14:24 UTC, azu reviewed
Probably, we need to define the loading logic for the plugin.

The plugin should be loaded from ... ?

- current directory(This PR)
- Honkit installed directory(Current maybe)
- config directory like ESLint
- configuration like `--cwd` flag
- other

Related works: https://github.com/eslint/eslint/blob/b5c8d7389bb2c5d4eae850b866832d099187818b/docs/user-guide/migrating-to-7.0.0.md#plugin-loading-change

For example, if loading from the current directory, the global installed `honkit` command looks into the local directory at first.
Is it ok?

2020-09-30 14:24 UTC, azu commented on packages/honkit/src/plugins/PluginResolver.ts
> +        for (const dir of [path.join(process.cwd(), "node_modules"), baseDir]) {
I do not realize what this logic does.
We need to write tests as expected behavior like https://github.com/textlint/textlint/blob/master/packages/textlint/test/textlint-module-resolver/textlint-module-resolver-test.js.  

Currently, `baseDir` always to be `""`.
https://github.com/honkit/honkit/blob/ed8ec44549c4ed9253c56dc9f24fda1f34449953/packages/honkit/src/plugins/loadForBook.ts#L22

So, It is just `require.resolve(pkgName)`.

- https://nodejs.org/api/modules.html#modules_all_together

2020-10-01 00:20 UTC, dogatana commented
To make following order clear, modify PluginResolver class and lordForBook.ts 

> - currentt directory(This PR)
> - Honkit installed directory(Current maybe)

I hope this can be applied for other cases by change the config.

> - config directory like ESLint
> - configuration like --cwd flag

On the other hand,

> We need to write tests as expected behavior

I can understand it, but it's hard for me.
I have no idea how to setup try-resolve stub, and it seems that further modification will be necessary for test.

2020-10-01 00:27 UTC, dogatana commented on packages/honkit/src/plugins/PluginResolver.ts
> +        for (const dir of [path.join(process.cwd(), "node_modules"), baseDir]) {
It's a quick way but too dirty..
I changed both PluginResolver.ts and loadForBook.ts to make it clear.

2020-10-02 16:01 UTC, azu requested changes
>  I have no idea how to setup try-resolve stub, and it seems that further modification will be necessary for test.

Good point. It is dificulet to test module's directory order.

We can add test case for `baseDirectories` and `resolvePluginPackageName` method behavior.
`PluginResolver` receive `baseDirectories` as options.
It means that the test case can pass the test's fixture directory to `PluginResolver`.

For example, 

- fixtures/
  - modules/
     - example
  - another_modules/
     - example
     - another_example

```ts
const resolver = PluginResolver({
  baseDirectories: [path.join(__dirname, "fixtures/modules")]
});
const fooPath = resolver.resolvePluginPackageName("example"); // it will resolve path.join(__dirname, "fixtures/modules/example/package.json");
assert.strictEqual(fooPath, path.join(__dirname, "fixtures/modules/example"));
```

and 

```ts
const resolver = PluginResolver({
  baseDirectories: [path.join(__dirname, "fixtures/modules"), path.join(__dirname, "fixtures/another_modules")]
});
const fooPath = resolver.resolvePluginPackageName("example");
assert.strictEqual(fooPath, path.join(__dirname, "fixtures/modules/example"));
const anotherFooPath = resolver.resolvePluginPackageName("another_example");
assert.strictEqual(anotherFooPath, path.join(__dirname, "fixtures/another_modules/another_example"));

```

and etc...

similar tests:

https://github.com/textlint/textlint/blob/master/packages/textlint/test/textlint-module-resolver/textlint-module-resolver-test.js
https://github.com/textlint/textlint/tree/master/packages/textlint/test/textlint-module-resolver

2020-10-02 16:08 UTC, azu commented on packages/honkit/src/plugins/loadForBook.ts
> +        baseDirectories: [path.join(process.cwd(), "node_modules")],
I don't really have much confidence about `require.resolve.paths` usage.
https://nodejs.org/api/modules.html#modules_require_resolve_request_options

2020-10-05 22:45 UTC, dogatana commented on packages/honkit/src/plugins/PluginResolver.ts
> +    resolvePluginPackageName(packageName, logger) {
I've changed.

2020-10-16 05:19 UTC, dogatana commented
I drop this.
The reason is the same as #132.

At last, I've created a theme plugin that solves #132 and #135.
It replaces "theme-default"  and works well with standard, npm-installed, honkit so far.
Thank you very much for your advice.

![image](https://user-images.githubusercontent.com/12756480/96215935-30ae6000-0fba-11eb-972b-7acea766a358.png)

2020-10-16 05:19 UTC, closed without merging