Bump highlight.js from 9.8.0 to 10.4.0
honkit/honkit pull request #162
Opened 2020-11-27 08:48 UTC by masnagam

This PR fixes #161:

* Import gitbook-plugin-highlight@2.0.3 as @honkit/honkit-plugin-highlight
* Replace gitbook-plugin-hightlight with @honkit/honkit-plugin-highlight in honkit/package.json
* The snapshots have been updated in order to solve test failures due to changes of highlight.js

TODO:

* gitbook-tester has been removed because it doesn't work with recent Node.js versions

2020-11-27 14:44 UTC, azu reviewed
Thanks!

![image](https://user-images.githubusercontent.com/19714/100459448-d4864200-3108-11eb-9df5-0257b4a6c3d8.png)
Preview URL: https://deploy-preview-162--honkit.netlify.app/templating/

Currently, Syntax Highlight does not work.
The reason is that preview build use `npm run build` for preview.
Probably, add `build` npm run-script to `@honkit/honkit-plugin-highlight` and resolve it.

Also, We think that class name difference between 9x and 10x.
(I do not know highlight.js in details)

2020-11-27 14:44 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/test/highlight.js
> +var tester = require('gitbook-tester');
https://github.com/vowstar/honkit-tester
Can we use honkit-tester instead of it?

2020-11-27 14:44 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/less/ebook.less
> +    /* From https://github.com/isagalaev/highlight.js/blob/9.8.0/src/styles/tomorrow.css */
We need to update this file based on https://github.com/highlightjs/highlight.js/blob/10-stable/src/styles/tomorrow.css

2020-11-27 14:44 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/less/night.less
> +/* http://jmblog.github.com/color-themes-for-google-code-highlightjs */
We also need to update this file based on https://github.com/highlightjs/highlight.js/blob/10-stable/src/styles/tomorrow-night-bright.css
But, Original theme is missing...

2020-11-27 14:44 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/package.json
> +    "prepublish": "mkdir -p css && lessc ./less/website.less > ./css/website.css; lessc ./less/ebook.less > ./css/ebook.css"
```
    "build": "lessc ./less/website.less ./css/website.css && lessc ./less/ebook.less ./css/ebook.css",
    "prepublish": "npm run build"
```

This change aims to support Windows and correct work on a preview build.
https://deploy-preview-162--honkit.netlify.app/templating/

2020-11-27 15:37 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/test/highlight.js
> +var tester = require('gitbook-tester');
I'm ok that remove this test if it is difficult.

2020-11-27 15:39 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/package.json
> +    "prepublish": "mkdir -p css && lessc ./less/website.less > ./css/website.css; lessc ./less/ebook.less > ./css/ebook.css"
`prepublish` is npm's lifecycle method.
you should not call it from `build` manually.

2020-11-28 02:08 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/test/highlight.js
> +var tester = require('gitbook-tester');
honkit-tester seems not to work properly...

honkit-tester tries to create a symbolic link called `@honkit/honkit-plugin-highlight`.  That causes an `ENOENT` error because there is no `@honkit` directory.

2020-11-28 02:19 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/less/ebook.less
> +    /* From https://github.com/isagalaev/highlight.js/blob/9.8.0/src/styles/tomorrow.css */
Solved at ae22829d757ac742c858e792c3d2e8c203737237

2020-11-28 02:20 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/less/night.less
> +/* http://jmblog.github.com/color-themes-for-google-code-highlightjs */
Solved at ae22829d757ac742c858e792c3d2e8c203737237

2020-11-28 02:21 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/package.json
> +    "prepublish": "mkdir -p css && lessc ./less/website.less > ./css/website.css; lessc ./less/ebook.less > ./css/ebook.css"
Solved at 15aa3d97406941529257eaa3149b7df3b6f39074

2020-11-28 02:23 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/test/highlight.js
> +var tester = require('gitbook-tester');
I like to leave this task as TODO.
I added descriptions about that in README.md.
See 37c45ab203986ddf665dbd0996956e6e080250c8.

2020-11-28 02:45 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/test/highlight.js
> +var tester = require('gitbook-tester');
Registered vowstar/honkit-tester#1

2020-11-28 08:26 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/test/highlight.js
> +var tester = require('gitbook-tester');
ok. thanks

2020-11-28 08:30 UTC, azu commented
![image](https://user-images.githubusercontent.com/19714/100497517-56c14580-319f-11eb-9e9d-f0b3bbb518b7.png)

We got the same result 🎉 

Thanks for PR!

2020-11-28 08:35 UTC, azu requested changes
I've added a comment.

Other things are LGTM.

2020-11-28 08:35 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/.npmignore
> +!css
We want to use `files` field in package.json instead of npmignore.


`files` is a allow list.
`npmignore` is a ignoring list.
We prefer to use allow list.

https://github.com/honkit/honkit/blob/5b52883ec63b18dc146e482aa355014f2f68d012/packages/honkit/package.json#L36-L40

2020-11-28 08:37 UTC, azu commented on packages/@honkit/honkit-plugin-highlight/.npmignore
> +!css
It means that we do not publish unnecessary files like `packages/@honkit/honkit-plugin-highlight/scripts/build-less.js`

2020-11-28 13:35 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/test/highlight.js
> +var tester = require('gitbook-tester');
vowstar/honkit-tester#1 has been fixed, but there are other issues which block to enable the tests.
That requires additional effort.

2020-11-28 13:42 UTC, masnagam commented on packages/@honkit/honkit-plugin-highlight/.npmignore
> +!css
Solved at 529d1f5a3f5772c7ab52992c85eb1d8cf78d5d1e.

Files listed below are included in the tarball:

```
npm notice === Tarball Contents ===
npm notice 822B   README.md
npm notice 1.8kB  css/ebook.css
npm notice 19.2kB css/website.css
npm notice 950B   index.js
npm notice 953B   package.json
```

2020-11-29 03:30 UTC, azu approved these changes
Perfect!

Thanks

2020-11-29 03:30 UTC, merged